name: counting_love_day
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # TODO: [utils]
  # hex color
  hexcolor: 3.0.1
  # toast notifications
  fluttertoast: 8.2.4
  # slider
  carousel_slider: 4.2.1
  # pinput number
  pinput: 4.0.0
  # bottom nav bar
  persistent_bottom_nav_bar: 5.0.2
  # log
  logger: 2.1.0
 
  # TODO: [images]
  # cached network image
  cached_network_image: 3.3.1
  # read svg image
  flutter_svg: 2.0.5
  # lottie
  lottie: 2.3.2

   # TODO: [icons]
  # icon flutter
  eva_icons_flutter: 3.1.0
  # icon ios
  cupertino_icons: 1.0.2

  # TODO: [services]
  # getX
  get: 4.6.5
  # save local with shared preferences
  shared_preferences: 2.2.2
  # dio service
  dio: 5.4.0
  # xml reading
  xml: 6.2.2
  # firebase
  firebase_core: 2.27.0
  # change package name
  change_app_package_name: 1.1.0
  share_plus: ^7.2.2
  flutter_rating_bar: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lotties/
    - assets/lotties/couple.json


