// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDksMFqErL78z8mDb-pcL9D-GQzNL8_sw',
    appId: '1:497921659842:android:22ecfc2877771bc3b97c5b',
    messagingSenderId: '497921659842',
    projectId: 'counting-love-day',
    storageBucket: 'counting-love-day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqyGqyqXVPC1zFnzQrFsInFLQs6C-xRk',
    appId: '1:497921659842:ios:f7eba047be0dc098b97c5b',
    messagingSenderId: '497921659842',
    projectId: 'counting-love-day',
    storageBucket: 'counting-love-day.appspot.com',
    iosClientId: '497921659842-0hn7uc05to3v3uuiq31sn1u3mpanbr29.apps.googleusercontent.com',
    iosBundleId: 'com.example.countingLoveDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvqyGqyqXVPC1zFnzQrFsInFLQs6C-xRk',
    appId: '1:497921659842:ios:fe57fe6399b41151b97c5b',
    messagingSenderId: '497921659842',
    projectId: 'counting-love-day',
    storageBucket: 'counting-love-day.appspot.com',
    iosClientId: '497921659842-skq6mde5gaucsuq0q6t0dfnm7j858e39.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
